Version=1
# false
Asset.SlowLoad=false

# false
Asset.CheckItemTexAndNames=false

# false
Multiplayer.Debug.Attack.Player=false

# false
Multiplayer.Debug.Follow.Player=false

# false
Multiplayer.Debug.SeeNonPvpZones=false

# true
Multiplayer.Debug.AnticlippingAlgorithm=true

# false
Multiplayer.DebugFlags.LocalPlayer.Enable=false

# false
Multiplayer.DebugFlags.LocalPlayer.Position=false

# false
Multiplayer.DebugFlags.LocalPlayer.Prediction=false

# false
Multiplayer.DebugFlags.LocalPlayer.State=false

# false
Multiplayer.DebugFlags.LocalPlayer.StateVariables=false

# false
Multiplayer.DebugFlags.LocalPlayer.Animation=false

# false
Multiplayer.DebugFlags.LocalPlayer.Variables=false

# false
Multiplayer.DebugFlags.RemotePlayer.Enable=false

# false
Multiplayer.DebugFlags.RemotePlayer.Position=false

# false
Multiplayer.DebugFlags.RemotePlayer.Prediction=false

# false
Multiplayer.DebugFlags.RemotePlayer.State=false

# false
Multiplayer.DebugFlags.RemotePlayer.StateVariables=false

# false
Multiplayer.DebugFlags.RemotePlayer.Animation=false

# false
Multiplayer.DebugFlags.RemotePlayer.Variables=false

# false
Multiplayer.DebugFlags.Animal.Enable=false

# false
Multiplayer.DebugFlags.Animal.Position=false

# false
Multiplayer.DebugFlags.Animal.Prediction=false

# false
Multiplayer.DebugFlags.Animal.State=false

# false
Multiplayer.DebugFlags.Animal.StateVariables=false

# false
Multiplayer.DebugFlags.Animal.Animation=false

# false
Multiplayer.DebugFlags.Animal.Variables=false

# false
Multiplayer.DebugFlags.Zombie.Enable=false

# false
Multiplayer.DebugFlags.Zombie.Position=false

# false
Multiplayer.DebugFlags.Zombie.Prediction=false

# false
Multiplayer.DebugFlags.Zombie.State=false

# false
Multiplayer.DebugFlags.Zombie.StateVariables=false

# false
Multiplayer.DebugFlags.Zombie.Animation=false

# false
Multiplayer.DebugFlags.Zombie.Variables=false

# false
Multiplayer.DebugFlags.DeadBody.Enable=false

# false
Multiplayer.DebugFlags.DeadBody.Position=false

# false
Cheat.Clock.Visible=false

# false
Cheat.Door.Unlock=false

# false
Cheat.Player.StartInvisible=false

# false
Cheat.Player.InvisibleSprint=false

# false
Cheat.Player.SeeEveryone=false

# false
Cheat.Player.UnlimitedCondition=false

# false
Cheat.Player.FastLooseXp=false

# false
Cheat.TimedAction.Instant=false

# false
Cheat.Vehicle.MechanicsAnywhere=false

# false
Cheat.Vehicle.StartWithoutKey=false

# false
Cheat.Window.Unlock=false

# false
Cheat.Farming.FastGrow=false

# true
CollideWithObstacles.Debug.SlideAwayFromWalls=true

# false
CollideWithObstacles.Render.Radius=false

# false
CollideWithObstacles.Render.Obstacles=false

# false
CollideWithObstacles.Render.Normals=false

# false
DeadBodyAtlas.Render=false

# true
WorldItemAtlas.Enable=true

# false
WorldItemAtlas.Render=false

# XXX
# false
DebugScenario.ForceLaunch=true

# false
Mechanics.Render.Hitbox=false

# false
Joypad.Render.UI=false

# true
Model.Render.LimitTextureSize=true

# false
Model.Render.Attachments=false

# false
Model.Render.Axis=false

# false
Model.Render.Bones=false

# false
Model.Render.Bounds=false

# false
Model.Render.ForceAlphaOne=false

# false
Model.Render.Lights=false

# false
Model.Render.MuzzleFlash=false

# false
Model.Render.SkipVehicles=false

# false
Model.Render.WeaponHitPoint=false

# false
Model.Render.Wireframe=false

# false
Model.Force.Skeleton=false

# false
Mod.Render.Loaded=false

# false
Pathfind.PathToMouse.AllowCrawl=false

# false
Pathfind.PathToMouse.AllowThump=false

# false
Pathfind.PathToMouse.Enable=false

# false
Pathfind.PathToMouse.IgnoreCrawlCost=false

# false
Pathfind.PathToMouse.RenderSuccessors=false

# false
Pathfind.Render.ChunkRegions=false

# false
Pathfind.Render.Path=false

# false
Pathfind.Render.Waiting=false

# true
Pathfind.SmoothPlayerPath=true

# true
Pathfind.UseNativeCode=true

# false
Pathfind.BorderFinder=false

# false
Threading.Pathfinding=false

# false
Physics.Render=false

# false
Physics.Render.PlayerLevelOnly=false

# false
Physics.Debug.Render.BallisticsControllers=false

# false
Physics.Debug.Render.BallisticsTargets=false

# false
Physics.Debug.Render.HighlightBallisticsTargets=false

# false
Polymap.Render.Clusters=false

# false
Polymap.Render.Connections=false

# false
Polymap.Render.Crawling=false

# false
Polymap.Render.LineClearCollide=false

# false
Polymap.Render.Nodes=false

# false
Tooltip.Info=false

# false
Tooltip.Attributes=false

# false
Tooltip.ModName=false

# false
Translation.Prefix=false

# false
UI.Render.Outline=false

# true
UI.DebugConsole.StartVisible=true

# true
UI.DebugConsole.DebugLog=true

# true
UI.DebugConsole.EchoCommand=true

# true
UI.DisableLogoState=true

# false
UI.DisableWelcomeMessage=true

# false
UI.HideDebugContextMenuOptions=false

# true
UI.UIShowResearchableEtc=true

# true
UI.uiShowContextMenuReportOptions=true

# false
Vehicle.CycleColor=false

# false
Vehicle.Render.Blood0=false

# false
Vehicle.Render.Blood50=false

# false
Vehicle.Render.Blood100=false

# false
Vehicle.Render.Damage0=false

# false
Vehicle.Render.Damage1=false

# false
Vehicle.Render.Damage2=false

# false
Vehicle.Render.Rust0=false

# false
Vehicle.Render.Rust50=false

# false
Vehicle.Render.Rust100=false

# false
Vehicle.Render.Outline=false

# false
Vehicle.Render.Area=false

# false
Vehicle.Render.Authorizations=false

# false
Vehicle.Render.InterpolateBuffer=false

# false
Vehicle.Render.AttackPositions=false

# false
Vehicle.Render.Exit=false

# false
Vehicle.Render.IntersectedSquares=false

# false
Vehicle.Render.TrailerPositions=false

# false
Vehicle.Spawn.Everywhere=false

# false
Sound.AmbientWallEmitters.Render=false

# false
Sound.WorldSound.Render=false

# false
Sound.ObjectAmbientEmitter.Render=false

# false
Sound.ParameterInside.Render=false

# false
Lighting.Render=false

# false
Skybox.Show=false

# false
WorldStreamer.SlowLoad=false

# false
DebugDraw.SkipVBODraw=false

# false
DebugDraw.SkipDrawNonSkinnedModel=false

# false
DebugDraw.SkipWorldShading=false

# false
DebugDraw.FishingZones=false

# false
GameProfiler.Enabled=false

# false
GameTime.Speed.Half=false

# false
GameTime.Speed.Quarter=false

# false
GameTime.Speed.Eighth=false

# false
GameTime.TimeOfDay.Freeze=false

# false
ThreadCrash.Enable=false

# false
ThreadCrash.MainThread.0=false

# false
ThreadCrash.MainThread.1=false

# false
ThreadCrash.MainThread.2=false

# false
ThreadCrash.RenderThread.0=false

# false
ThreadCrash.RenderThread.1=false

# false
ThreadCrash.RenderThread.2=false

# false
ThreadCrash.GameLoadingThread.0=false

# false
Thumpable.IsoWindow.ResetCurrentCellWindows=false

# false
Thumpable.IsoBarricade.BarricadeCurrentCellWindows.FullPlank=false

# false
Thumpable.IsoBarricade.BarricadeCurrentCellWindows.HalfPlank=false

# false
Thumpable.IsoBarricade.BarricadeCurrentCellWindows.FullMetalBars=false

# false
Thumpable.IsoBarricade.BarBarricadeCurrentCellWindows.MetalPlate=false

# false
Thumpable.IsoBarricade.RemoveBarricadeCurrentCellWindows=false

# false
World.ChunkMap.5x5=false

# false
World.ChunkMap.7x7=false

# false
World.ChunkMap.9x9=false

# false
World.ChunkMap.11x11=false

# false
World.ChunkMap.13x13=false

# false
Zombie.Render.CanCrawlUnderVehicle=false

# false
Zombie.Render.FakeDead=false

# false
Zombie.Render.Memory=false

# false
Zombie.Render.ViewDistance=false

# false
Zombie.Outfit.Random=false

# true
Entity.DebugUI=true

# false
Zombie.Imposter.RenderImposters=false

# false
Zombie.Imposter.PreviewBlend=false

# false
Zombie.Imposter.PreviewCard=false

# false
Zombie.Imposter.Blend=false

# false
Render.Test.FSQuad=false

# true
Zombie.Animation.DelayInvisible=true

# false
Zombie.Render.Instanced=false

# false
Instancing.Buffer.Copy=false

# false
Threading.Lighting=false

# false
Lighting.SplitUpdate=false

# false
Threading.Ambient=false

# false
Visibility.DisplayLines=false

# true
Visibility.UseNew=true

# false
Visibility.PreviewTiles=false

# true
FBORenderLevels.CheapOcclusionCount=true

# false
Threading.RecalculateGridStacks=false

# false
Threading.Sound=false

# false
Threading.World=false

# true
Threading.ModelSlotInit=true

# false
Threading.Animation=false

# false
Rendering.DelayObjects=false

# false
Checks.BoundShader=false

# false
Checks.BoundTextures=false

# true
Checks.LuaOwnerThread=true

# false
Checks.ObjectPool.Contains=false

# false
Checks.SlowLuaEvents=false

# true
IsoSprite.Render.Sprites=true

# true
IsoSprite.Render.Models=true

# false
IsoSprite.Render.MovingObjectEdges=false

# false
IsoSprite.Render.DropShadowEdges=false

# true
IsoSprite.Render.NearestMagFilterAtMinZoom=true

# false
IsoSprite.Render.ItemHeight=false

# false
IsoSprite.Render.Surface=false

# false
IsoSprite.Render.TextureWrap.ClampToEdge=false

# false
IsoSprite.Render.TextureWrap.Repeat=false

# false
IsoSprite.Render.ForceLinearMagFilter=false

# false
IsoSprite.Render.ForceNearestMagFilter=false

# false
IsoSprite.Render.ForceNearestMipMapping=false

# false
IsoSprite.Render.CharacterMipmapColors=false

# false
IsoSprite.Render.WorldMipmapColors=false

# true
Network.Client.MainLoop=true

# true
Network.Client.UpdateZombiesFromPacket=true

# true
Network.Client.SyncIsoObject=true

# true
Network.Server.SyncIsoObject=true

# true
Network.PublicServerUtil.Enabled=true

# true
OffscreenBuffer.Render=true

# true
Terrain.RenderTiles.Enable=true

# true
Terrain.RenderTiles.NewRender=true

# true
Terrain.RenderTiles.Shadows=true

# true
Terrain.RenderTiles.BloodDecals=true

# true
Terrain.RenderTiles.Water=true

# true
Terrain.RenderTiles.WaterShore=true

# true
Terrain.RenderTiles.WaterBody=true

# true
Terrain.RenderTiles.Lua=true

# true
Terrain.RenderTiles.VegetationCorpses=true

# true
Terrain.RenderTiles.MinusFloorCharacters=true

# true
Terrain.RenderTiles.RenderGridSquares=true

# true
Terrain.RenderTiles.RenderSprites=true

# true
Terrain.RenderTiles.OverlaySprites=true

# true
Terrain.RenderTiles.AttachedAnimSprites=true

# true
Terrain.RenderTiles.AttachedChildren=true

# true
Terrain.RenderTiles.AttachedWallBloodSplats=true

# true
Terrain.RenderTiles.UseShaders=true

# false
Terrain.RenderTiles.HighContrastBg=false

# true
Terrain.RenderTiles.Cutaway=true

# false
Terrain.RenderTiles.ForceFullAlpha=false

# true
Terrain.RenderTiles.RenderContainerHighlight=true

# true
Terrain.RenderTiles.IsoGridSquare.RenderMinusFloor=true

# true
Terrain.RenderTiles.IsoGridSquare.DoorsAndWalls=true

# true
Terrain.RenderTiles.IsoGridSquare.DoorsAndWallsSL=true

# true
Terrain.RenderTiles.IsoGridSquare.Objects=true

# true
Terrain.RenderTiles.IsoGridSquare.MeshCutDown=true

# true
Terrain.RenderTiles.IsoGridSquare.IsoPadding=true

# true
Terrain.RenderTiles.IsoGridSquare.IsoPaddingDeDiamond=true

# true
Terrain.RenderTiles.IsoGridSquare.IsoPaddingAttached=true

# true
Terrain.RenderTiles.IsoGridSquare.ShoreFade=true

# true
Terrain.RenderTiles.IsoGridSquare.Walls.NW=true

# true
Terrain.RenderTiles.IsoGridSquare.Walls.W=true

# true
Terrain.RenderTiles.IsoGridSquare.Walls.N=true

# true
Terrain.RenderTiles.IsoGridSquare.Walls.Render=true

# true
Terrain.RenderTiles.IsoGridSquare.Walls.Lighting=true

# false
Terrain.RenderTiles.IsoGridSquare.Walls.LightingDebug=false

# false
Terrain.RenderTiles.IsoGridSquare.Walls.LightingOldDebug=false

# true
Terrain.RenderTiles.IsoGridSquare.Walls.AttachedSprites=true

# true
Terrain.RenderTiles.IsoGridSquare.Floor.Lighting=true

# false
Terrain.RenderTiles.IsoGridSquare.Floor.LightingOld=false

# false
Terrain.RenderTiles.IsoGridSquare.Floor.LightingDebug=false

# true
Weather.Fog=true

# true
Weather.Fx=true

# true
Weather.Snow=true

# false
Weather.ShowUsablePuddles=false

# true
Weather.WaterPuddles=true

# false
Animation.AnimLayer.Debug.LogStateChanges=false

# false
Animation.AnimLayer.Debug.AllowAnimNodeOverride=false

# false
Animation.AnimLayer.Debug.LogNodeConditions=false

# true
Animation.SharedSkeles.Enabled=true

# true
Animation.SharedSkeles.AllowLerping=true

# false
Animation.DancingDoors=false

# false
Animation.Debug=false

# false
Animation.DisableRagdolls=false

# true
Animation.AllowEarlyTransitionOut=true

# false
Animation.Render.Picker=false

# false
Animation.BlendUseFbx=false

# false
Animation.DisableAnimationBlends=false

# false
Character.Create.AllOutfits=false

# false
Character.Debug.Render.AimCone=false

# false
Character.Debug.Render.Angle=false

# false
Character.Debug.Render.TestDotSide=false

# false
Character.Debug.Render.DeferredMovement=false

# false
Character.Debug.Render.DeferredRotation=false

# false
Character.Debug.Render.Translation_Data=false

# false
Character.Debug.Render.Bip01=false

# false
Character.Debug.Render.HandBones.Primary=false

# false
Character.Debug.Render.HandBones.Secondary=false

# false
Character.Debug.Render.SkipCharacters=false

# false
Character.Debug.Render.Vision=false

# false
Character.Debug.Render.DisplayRoomAndZombiesZone=false

# false
Character.Debug.Render.FMODRoomType=false

# false
Character.Debug.Render.CarStopDebug=false

# false
Character.Debug.Render.MeleeOutline=false

# false
Character.Debug.Render.AimVector=false

# false
Character.Debug.Render.ClimbRope=false

# false
Character.Debug.Render.ExplosionHitDirection=false

# false
Character.Debug.Animate.DeferredRotationsOnly=false

# false
Character.Debug.Animate.NoBoneMasks=false

# false
Character.Debug.Animate.NoBoneTwists=false

# false
Character.Debug.Animate.AlwaysAimTwist=false

# false
Character.Debug.Animate.ZeroCounterRotation=false

# true
Character.Debug.Animate.KeepAtOrigin=true

# false
Character.Debug.Ragdoll.Render.Enable=false

# false
Character.Debug.Ragdoll.Render.Body=false

# false
Character.Debug.Ragdoll.Render.PelvisLocation=false

# false
Character.Debug.Ragdoll.Render.BodySinglePart=false

# false
Character.Debug.Ragdoll.Render.Skeleton=false

# false
Character.Debug.Ragdoll.Render.SkeletonSinglePart=false

# true
Character.Debug.Ragdoll.Physics.PhysicsHitReaction=true

# false
Character.Debug.Ragdoll.Physics.AllowJointConstraintDetach=false

# false
Character.Debug.Ragdoll.Debug=false

# true
Character.Debug.Ragdoll.SimulationActive=true

# true
Character.Debug.Ragdoll.EnableInitialVelocities=true

# false
Character.Debug.DebugVariables=false

# false
Character.Debug.AlwaysTripOverFence=false

# false
Character.Debug.PlaySoundWhenInvisible=false

# true
Character.Debug.UpdateAlpha=true

# false
Character.Debug.UpdateAlphaEighthSpeed=false

# false
Character.Debug.AlwaysHitTarget=false

# false
Character.Debug.UseNewClimbingCalculations=false

# false
FBORenderChunk.BulletTracers=false

# false
FBORenderChunk.CombinedFBO=false

# false
FBORenderChunk.CorpsesInChunkTexture=false

# true
FBORenderChunk.DepthTestAll=true

# true
FBORenderChunk.FixJigglyModels=true

# false
FBORenderChunk.HighResChunkTextures=false

# false
FBORenderChunk.ForceAlphaAndTargetOne=false

# false
FBORenderChunk.ForceAlphaToTarget=false

# false
FBORenderChunk.ForceSkyLightLevel=false

# false
FBORenderChunk.ItemsInChunkTexture=false

# true
FBORenderChunk.MipMaps=true

# false
FBORenderChunk.NoLighting=false

# true
FBORenderChunk.RenderChunkTextures=true

# false
FBORenderChunk.RenderMustSeeSquares=false

# true
FBORenderChunk.RenderTranslucentFloor=true

# true
FBORenderChunk.RenderTranslucentNonFloor=true

# true
FBORenderChunk.RenderVisionPolygon=true

# false
FBORenderChunk.RenderWallLines=false

# false
FBORenderChunk.SeamFix1=false

# true
FBORenderChunk.SeamFix2=true

# true
FBORenderChunk.UpdateSquareLightInfo=true

# true
FBORenderChunk.UseWeatherShader=true

# false
Statistics.DisplayAllDebugStats=false
