task :default => :build

MOD_ID   = "ZBSpec"
MOD_TYPE = "shared"
VERSIONS = {
  "42" => "17",
}

VERSIONS.each do |ver, jdk_ver|
  desc "build for #{ver}"
  task "build:#{ver}" do
    Dir.chdir("java") do
      env = {
        "JAVA_HOME" => "/Library/Java/JavaVirtualMachines/openjdk-#{jdk_ver}.jdk/Contents/Home"
      }
      sh env, "gradle build -PZVersion=#{ver}"
    end
    dst_dir = "common/media/java/#{MOD_TYPE}"
    FileUtils.mkdir_p dst_dir
    FileUtils.mv "java/build/libs/#{MOD_ID}-#{ver}.jar", "#{dst_dir}/#{MOD_ID}.jar"
  end
end

desc "build test map"
task "build:map" do
  sh "~/tools/zomboid/compiler.rb testmap.yml -V 41.0 -o 41/media/maps/TestMap/"
  sh "~/tools/zomboid/dumper.rb 41/media/maps/TestMap/*"

  sh "~/tools/zomboid/compiler.rb testmap.yml -V 42.0 -o 42/media/maps/TestMap/"
  sh "~/tools/zomboid/dumper.rb 42/media/maps/TestMap/*"
end

desc "build all"
task :build => VERSIONS.keys.map { |ver| "build:#{ver}" } + ["build:map"]
