Version=4
# Off
Packet=Debug

# Off
NetworkFileDebug=Off

# Error
Network=Error

# General
General=General

# Off
DetailedInfo=Off

# General
Lua=General

# General
Mod=General

# Off
Sound=Off

# Off
Zombie=Off

# Off
Combat=Off

# Off
Objects=Off

# Off
Fireplace=Off

# Off
Radio=Off

# Off
MapLoading=Off

# Off
Clothing=Off

# Off
Animation=Off

# Off
AnimationDetailed=Off

# Off
Asset=Off

# Off
Script=Off

# Off
Shader=Off

# Off
Sprite=Off

# Off
Input=Off

# Off
Recipe=Off

# Off
ActionSystem=Off

# Off
ActionSystemEvents=Off

# Off
IsoRegion=Off

# Off
FileIO=Off

# General
Multiplayer=General

# Off
Damage=Off

# Off
Death=Off

# Off
Discord=Off

# Off
Statistic=Off

# Off
Vehicle=Off

# Off
Voice=Off

# Off
Checksum=Off

# Off
Animal=Off

# Off
ItemPicker=Off

# Off
CraftLogic=Off

# Off
Action=Off

# Off
Entity=Off

# Off
Lightning=Off

# Off
Grapple=Off

# Off
ExitDebug=Off

# Off
BodyDamage=Off

# Off
Xml=Off

# Off
Physics=Off

# Off
Ballistics=Off

# Off
Ragdoll=Off

# Off
PZBullet=Off

# Off
ModelManager=Off

# Off
LoadAnimation=Off

# Off
Zone=Off

# Off
WorldGen=Off

# Off
Foraging=Off

# Off
Saving=Off

# Off
Fluid=Off

# Off
Energy=Off

# Off
Translation=Off

# Off
Moveable=Off

# Off
Basement=Off

# Off
FallDamage=Off

# Off
ImGui=Off

# Off
CharacterTrait=Off
